from fastapi import APIRouter, HTTPException
from backend.schemas.api_models import ChatRequest
from backend.agent.workflow import research_agent

router = APIRouter(prefix="/tools", tags=["Research Tools"])

async def run_agent(message: str, force_mode: str = None):
    """
    Orchestrates the execution of the LangGraph research agent.

    This helper function initializes the graph state and handles the execution logic.
    If 'force_mode' is provided, it prepends specific instructions to the user's message 
    to strongly steer the agent's internal router toward a specific tool.

    Args:
        message (str): The user's input query or command.
        force_mode (str, optional): A specific tool category (e.g., 'summarize') to 
            enforce. Defaults to None.

    Returns:
        dict: A dictionary containing the final 'answer' generated by the agent.

    Raises:
        HTTPException: Returns a 500 error if the graph execution encounters an exception.
    """
    try:
        initial_state = {"question": message, "messages": []}
        
        # If a specific mode is forced, we engineer the prompt to ensure 
        # the Router Node classifies it correctly.
        if force_mode:
            if force_mode == "summarize": message = "Summarize this document: " + message
            elif force_mode == "compare": message = "Compare these documents: " + message
            elif force_mode == "extract": message = "Extract data from: " + message
            elif force_mode == "insight": message = "Generate insights for: " + message
            
            initial_state["question"] = message

        result = research_agent.invoke(initial_state)
        return {
            "answer": result["generation"]
        }
    except Exception as e:
        print(f"Error executing agent: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# --- 1. Main Auto-Routing Endpoint ---
@router.post("/chat")
async def auto_chat(request: ChatRequest):
    """
    The primary chat endpoint that relies on the AI to decide the best tool.
    
    This endpoint sends the raw user query to the router node, allowing the system 
    to dynamically choose between Summarization, Q&A, Comparison, etc.
    """
    return await run_agent(request.message)

# --- 2. Specific Function Endpoints ---
@router.post("/summarize")
async def force_summarize(request: ChatRequest):
    """
    Explicitly forces the agent to perform a Summarization task.
    Useful for UI buttons like "Summarize This".
    """
    return await run_agent(request.message, force_mode="summarize")

@router.post("/compare")
async def force_compare(request: ChatRequest):
    """
    Explicitly forces the agent to perform a Comparison task.
    Useful for UI buttons like "Compare Docs".
    """
    return await run_agent(request.message, force_mode="compare")

@router.post("/extract")
async def force_extract(request: ChatRequest):
    """
    Explicitly forces the agent to perform Data Extraction.
    Useful for retrieving specific metrics or tables.
    """
    return await run_agent(request.message, force_mode="extract")

@router.post("/insight")
async def force_insight(request: ChatRequest):
    """
    Explicitly forces the agent to generate Insights.
    Useful for requests asking for "Analysis" or "Recommendations".
    """
    return await run_agent(request.message, force_mode="insight")