import operator
from typing import Annotated, List, TypedDict
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """
    The shared execution state of the research agent graph.

    This dictionary acts as the "memory" passed between every node in the workflow.
    It holds the conversation history, the current inputs, retrieved context, 
    and the final output.

    Attributes:
        messages (List[BaseMessage]): A historical log of the conversation. 
            The `Annotated[..., operator.add]` syntax ensures that when a node 
            returns a 'messages' key, the new messages are APPENDED to this list 
            rather than overwriting it.
        question (str): The original user query or hypothesis being researched.
        documents (List[str]): A list of formatted string content retrieved from 
            the vector store. These serve as the context for the LLM.
        generation (str): The most recent output generated by a tool or the router. 
            This serves as the variable for conditional logic (e.g., deciding 
            which path to take next) or the final answer.
    """

    messages: Annotated[List[BaseMessage], operator.add]
    
    question: str
    
    documents: List[str]

    generation: str
    
    conversation_id: int

    needs_search: bool